export const ROUTES = {
  DASHBOARD: '/dashboard',
  PATIENTS: '/patients',
  PATIENTS_NEW: '/patients/new',
  APPOINTMENTS: '/appointments',
  APPOINTMENTS_CALENDAR: '/appointments/calendar',
  APPOINTMENTS_NEW: '/appointments/new',
  MEDICAL_RECORDS: '/medical-records',
  MEDICAL_RECORDS_NEW: '/medical-records/new',
  EMPLOYEES: '/employees',
  EMPLOYEES_NEW: '/employees/new',
  DEPARTMENTS: '/departments',
  DEPARTMENTS_NEW: '/departments/new',
  HR_DASHBOARD: '/hr/dashboard',
  HR_EMPLOYEES: '/hr/employees',
  HR_ATTENDANCE: '/hr/attendance',
  HR_PAYROLL: '/hr/payroll',
  PHARMACY_DASHBOARD: '/pharmacy/dashboard',
  PHARMACY_MEDICATIONS: '/pharmacy/medications',
  PHARMACY_INVENTORY: '/pharmacy/inventory',
  PHARMACY_PRESCRIPTIONS: '/pharmacy/prescriptions',
  SERVICES: '/services',
  SERVICES_NEW: '/services/new',
  INVOICES: '/invoices',
  INVOICES_NEW: '/invoices/new',
  INVENTORY: '/inventory',
  INVENTORY_NEW: '/inventory/new'
} as const;

